# Generated by Django 3.2.8 on 2023-05-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shower', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_angle', models.IntegerField()),
                ('R_radiate', models.IntegerField()),
                ('S_radiate', models.IntegerField()),
                ('D_radiate', models.IntegerField()),
                ('b_anglee', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='DataItem',
        ),
    ]
