# Generated by Django 4.2.3 on 2023-07-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shower", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.IntegerField()),
                ("humility", models.IntegerField()),
                ("lighten", models.IntegerField()),
                ("date", models.DateTimeField()),
            ],
            options={
                "db_table": "SOLAR",
            },
        ),
        migrations.DeleteModel(
            name="DataItem",
        ),
    ]
