# Generated by Django 4.2.3 on 2023-07-07 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shower", "0002_sensordata_delete_dataitem"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="sensordata",
            table="SOLARS",
        ),
    ]
