# Generated by Django 4.2.3 on 2023-07-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shower", "0004_alter_sensordata_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensordata",
            name="humility",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="lighten",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="temperature",
            field=models.FloatField(),
        ),
    ]
