# Generated by Django 4.2.3 on 2023-07-07 13:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shower", "0006_alter_sensordata_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="sensordata",
            table="solar",
        ),
    ]
