# Generated by Django 4.2.3 on 2023-07-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shower", "0007_alter_sensordata_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarningData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.FloatField()),
                ("date", models.DateTimeField()),
                ("warning", models.TextField()),
            ],
            options={
                "db_table": "warning_list",
            },
        ),
    ]
